project:
  type: website

website:
  title: "Drake Music & Chart Analytics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: songstats.qmd
        text: Songstats Track
      - href: data.qmd
        text: Data Explorer
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
